POST http://localhost:8080/books
Content-Type: application/json

{
  "name": "Pies który jeździł samochodem",
  "pages": 20
}

###
GET http://localhost:8080/books

###
POST http://localhost:8080/books/d3131808-637c-4540-adcd-0d6f8825a633
Content-Type: application/json

{
  "comment": "Błąd w tytule 2"
}