###not existing endpoint
GET http://localhost:8080/

###list
GET http://localhost:8080/companies

###find
GET http://localhost:8080/companies?employeesFrom=10&employeesTo=100

###find by name
GET http://localhost:8080/companies/findByName?namePrefix=A&nameSuffix=A

###get by id
GET http://localhost:8080/companies/56dc0a7e-288a-4fa0-97b0-35dd1e1abb9c

###create random
POST http://localhost:8080/companies/random

###create many random
POST http://localhost:8080/companies/random/100

###delete by id
DELETE http://localhost:8080/companies/e22fe38d-e799-469e-b1cb-94ec31cc59bf

###delete all
DELETE http://localhost:8080/companies