version: '3.8'
services:
  mongodb:
    image: mongo:5.0.10
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
      - MONGO_INITDB_DATABASE=test
#  native-agent-run:
#    volumes:
#      - ./data-mongodb-lambda-graalvm/build/libs/:/home/app/libs/
#      - ./data-mongodb-lambda-graalvm/src/main/resources/META-INF/native-image/:/home/app/agent-output/
#    build:
#      context: .
#      dockerfile: ./data-mongodb-lambda-graalvm/build/docker/native-main/DockerfileNative
#      target: graalvm
#    command: bash -c "java -agentlib:native-image-agent=config-output-dir=/home/app/agent-output,experimental-class-define-support -cp $$(find . -name '*-all.jar') com.LocalRunner"
#    env_file:
#      - .env
  native-agent-test:
    volumes:
      - ./src/main/resources/META-INF/native-image/:/home/app/agent-output/
    build:
      context: .
      dockerfile: ./scripts/DockerfileNativeAgentTest
    entrypoint: bash -c "cp -rf /var/task/car-data-mongodb-lambda-graalvm/build/native/agent-output/test/* /home/app/agent-output"
  native-test:
    image: mvppl123/graalvm:java17-0.0.1
    working_dir: /home
    volumes:
      - ./:/home
    command: bash -c "./gradlew car-data-mongodb-lambda-graalvm:nativeTest"
  local-run:
    image: car-data-mongodb-lambda-graalvm:latest
    ports:
      - "9001:8080"
    environment:
      LOGGER_LEVELS_COM_DISPLATE: DEBUG
    volumes:
      - ./aws-lambda-rie:/aws-lambda-rie
    entrypoint: bash -c "cp -R /function /var/task && /aws-lambda-rie"
    env_file:
      - .env