micronaut:
  application:
    name: data-mongodb
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: mongodb://${MONGO_USER:user}:${MONGO_PASSWORD:user}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test?authSource=admin
