POST http://localhost:8080/books
Content-Type: application/json

{
  "name": "Pies który jeździł samochodem",
  "pages": 20
}

###
GET http://localhost:8080/books

###
GET http://localhost:8080/books?available=false

###
GET http://localhost:8080/books?available=true

###
POST http://localhost:8080/books/9a6b0303-8aeb-4c0e-a2ca-71f8e0b4b592/comment
Content-Type: application/json

{
  "comment": "Błąd w tytule 2"
}

###
PUT http://localhost:8080/books/a59793ad-26f9-4088-95bb-c663ac79d798/order
Content-Type: application/json

{
  "order": 1
}

###
PUT http://localhost:8080/books/a59793ad-26f9-4088-95bb-c663ac79d798/unavailable
Content-Type: application/json


###
PUT http://localhost:8080/books/9a6b0303-8aeb-4c0e-a2ca-71f8e0b4b592/available
Content-Type: application/json
